// <auto-generated />
namespace Oblig_3_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addUserToDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUserToDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202002191151223_addUserToDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
